"""Create flyer_items table

Revision ID: 8db465195c95
Revises: 
Create Date: 2025-05-03 23:04:09.060423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db465195c95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flyer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sellingUnit', sa.String(), nullable=False),
    sa.Column('sellingValue', sa.Float(), nullable=True),
    sa.Column('measuredQuantityValue', sa.Float(), nullable=True),
    sa.Column('measuredQuantityUnit', sa.String(), nullable=True),
    sa.Column('store', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flyer_items_id'), 'flyer_items', ['id'], unique=False)
    op.create_index(op.f('ix_flyer_items_name'), 'flyer_items', ['name'], unique=False)
    op.create_index(op.f('ix_flyer_items_store'), 'flyer_items', ['store'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flyer_items_store'), table_name='flyer_items')
    op.drop_index(op.f('ix_flyer_items_name'), table_name='flyer_items')
    op.drop_index(op.f('ix_flyer_items_id'), table_name='flyer_items')
    op.drop_table('flyer_items')
    # ### end Alembic commands ###
